version: '3.7'
services:
  db:
    image: mysql:8.0
    restart: always
    ports:
      - "4000:4000"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
      ALLOW_EMPTY_PASSWORD: yes

  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: 'laravelapp'
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
